CREATE TABLE IDENTIFICATION_TYPE (
    IDENTIFICATION_TYPE_ID BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    IDENTIFICATION_TYPE VARCHAR(255) NOT NULL
);

CREATE TABLE PERSON (
    PERSON_ID BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ID_IDENTIFICATION_TYPE BIGINT NOT NULL,
    IDENTIFICATION_NUMBER VARCHAR(255) NOT NULL,
    FIRST_NAME VARCHAR(255),
    LAST_NAME VARCHAR(255),
    GENRE CHAR(1),
    BIRTH_DATE DATE,
    PHONE_NUMBER VARCHAR(255),
    COUNTRY VARCHAR(255),
    PROVINCE VARCHAR(255),
    CITY VARCHAR(255),
    RESIDENCE VARCHAR(255),
    EMAIL VARCHAR(255) NOT NULL,
    ACCESS_KEY VARCHAR(255) NOT NULL,
    EXTERNAL_LOGIN_SOURCE VARCHAR(255),
    ENABLED BOOLEAN,
    VERIFIED BOOLEAN,
    FAILED_LOGIN_ATTEMPTS INTEGER,
    FOREIGN KEY (ID_IDENTIFICATION_TYPE) REFERENCES IDENTIFICATION_TYPE (IDENTIFICATION_TYPE_ID)
);

CREATE TABLE PERSON_POSITION (
    PERSON_POSITION_ID BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    PERSON_ID BIGINT NOT NULL,
    POSITION_ID BIGINT NOT NULL,
    FOREIGN KEY (PERSON_ID) REFERENCES PERSON (PERSON_ID),
    FOREIGN KEY (POSITION_ID) REFERENCES POSITION (POSITION_ID)
);

CREATE TABLE POSITION (
    POSITION_ID BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    POSITION_NAME VARCHAR(255),
    DETAIL VARCHAR(255)
);

CREATE TABLE POSITION_PRIVILEGE (
    POSITION_PRIVILEGE_ID BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    POSITION_ID BIGINT NOT NULL,
    PRIVILEGE_ID BIGINT NOT NULL,
    FOREIGN KEY (POSITION_ID) REFERENCES POSITION (POSITION_ID),
    FOREIGN KEY (PRIVILEGE_ID) REFERENCES PRIVILEGE (PRIVILEGE_ID)
);

CREATE TABLE PRIVILEGE (
    PRIVILEGE_ID BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    PRIVILEGE_NAME VARCHAR(255),
    DETAIL VARCHAR(255)
);

